# syntax=docker/dockerfile:1
FROM node:18-alpine AS build

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

# Install dependencies
RUN \
if [ -f package.json ]; then \
  npm install; \
elif [ -f yarn.lock ]; then \
  yarn install; \
elif [ -f pnpm-lock.yaml]; then \
  pnpm install; \
fi

# Bundle app source
COPY . .

# Build the app
RUN npm run build

# Port to expose
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
