# Description: Dockerfile for the FastAPI application
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the dependencies file to the working directory
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the contents of the api folder to the working directory`
COPY . .

# Expose the port the app runs on and run the app
CMD ["uvicorn", "main:app", "--host","0.0.0.0", "--port", "80"]
